/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 13e2e3aaba07b727a0ca2ea8d679b9ec)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "CodeGeneratorAgent" | "UserAppSandboxService" | "DORateLimitStore";
	}
	interface Env {
		VibecoderStore: KVNamespace;
		TEMPLATES_REPOSITORY: "https://github.com/cloudflare/vibesdk-templates";
		ALLOWED_EMAIL: "";
		DISPATCH_NAMESPACE: "vibesdk-default-namespace";
		ENABLE_READ_REPLICAS: "true";
		CLOUDFLARE_AI_GATEWAY: "vibesdk-gateway";
		CUSTOM_PREVIEW_DOMAIN: "escoladeautomacao.com";
		MAX_SANDBOX_INSTANCES: "10";
		SANDBOX_INSTANCE_TYPE: "standard-3";
		USE_CLOUDFLARE_IMAGES: false;
		CUSTOM_DOMAIN: string;
		ENVIRONMENT: string;
		CLOUDFLARE_API_TOKEN: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		CLOUDFLARE_AI_GATEWAY_TOKEN: string;
		CLOUDFLARE_AI_GATEWAY_URL: string;
		GOOGLE_AI_STUDIO_API_KEY: string;
		OPENAI_API_KEY: string;
		JWT_SECRET: string;
		WEBHOOK_SECRET: string;
		USE_TUNNEL_FOR_PREVIEW: string;
		CodeGenObject: DurableObjectNamespace<import("./worker/index").CodeGeneratorAgent>;
		Sandbox: DurableObjectNamespace<import("./worker/index").UserAppSandboxService>;
		DORateLimitStore: DurableObjectNamespace<import("./worker/index").DORateLimitStore>;
		TEMPLATES_BUCKET: R2Bucket;
		DB: D1Database;
		DISPATCHER: DispatchNamespace;
		API_RATE_LIMITER: RateLimit;
		AUTH_RATE_LIMITER: RateLimit;
		AI: Ai;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TEMPLATES_REPOSITORY" | "ALLOWED_EMAIL" | "DISPATCH_NAMESPACE" | "ENABLE_READ_REPLICAS" | "CLOUDFLARE_AI_GATEWAY" | "CUSTOM_PREVIEW_DOMAIN" | "MAX_SANDBOX_INSTANCES" | "SANDBOX_INSTANCE_TYPE" | "USE_CLOUDFLARE_IMAGES" | "CUSTOM_DOMAIN" | "ENVIRONMENT" | "CLOUDFLARE_API_TOKEN" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_AI_GATEWAY_TOKEN" | "CLOUDFLARE_AI_GATEWAY_URL" | "GOOGLE_AI_STUDIO_API_KEY" | "OPENAI_API_KEY" | "JWT_SECRET" | "WEBHOOK_SECRET" | "USE_TUNNEL_FOR_PREVIEW">> {}
}
